name: CI

on:
  pull_request:
  push:
    branches: [ main, master, prod ]

# The list of permissions is explained on the GitHub doc:
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions:
  # Write permissions is needed to create a new release
  contents: write
  # allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  linter:
    name: golangci-lint on a PR or from a tag
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
        with:
          # We need to define the fetch-depth to 0 so that we can get the commit ID of the master branch
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          check-latest: true
      - name: Get lint-go-version script
        run: wget --output-document=$(pwd)/lint-go-version https://sc-devtools.s3.eu-west-1.amazonaws.com/golang-ci/lint-go-version
      - name: Execute lint-go-version script
        run: bash $(pwd)/lint-go-version
      - name: Get golangci-lint configuration file
        run: wget --output-document=$(pwd)/.golangci.yml https://sc-devtools.s3.eu-west-1.amazonaws.com/golang-ci/golangci.yml
      - name: "Execute golangci-lint on a pull request"
        uses: Scalingo/golangci-lint-action@v8
        with:
          # The `only-new-issues` flag is not working (https://github.com/golangci/golangci-lint-action/issues/531).
          # We rather decided to use the suggestion from the FAQ (https://golangci-lint.run/docs/welcome/faq/#how-to-integrate-golangci-lint-into-a-large-project-with-thousands-of-issues) and use `--new-from-rev`
          # only-new-issues: false
          args: "--config=$(pwd)/.golangci.yml --new-from-rev=${{ github.event.pull_request.base.sha }}"

  tests:
    name: Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          check-latest: true
      - name: Import test environment variables
        id: import-env
        shell: bash
        run: test -f .env.test && cat .env.test >> "$GITHUB_ENV"
      - name: Execute the unit tests
        run: go test -race ./...

