name: Release to production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release (e.g. v1.2.3)"
        required: true
  push:
    tags:
      - "v*.*.*"   # optional: allow tag pushes to start this

permissions:
  contents: write          # needed to create the release
  deployments: write       # recommended for environment/deployment updates

jobs:
  create_release:
    name: Await approval → Create GitHub Release
    runs-on: ubuntu-latest
    environment:
      name: production        # <-- triggers the approval gate in the environment
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - run: |
          CGO_ENABLED=0 go build -ldflags "-s -w -X main.version=${GITHUB_SHA}" -o dist/test-gha-deployment .
          tar -czf dist/test-gha-deployment.tar.gz -C dist test-gha-deployment
          sha256sum dist/test-gha-deployment > dist/SHA256SUMS
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 0
