name: publish-staging
on:
  push:
    branches: [ main, master ]   # triggers on both branches

permissions:
  contents: write                # required to push tags & create releases

jobs:
  prerelease:
    runs-on: ubuntu-latest
    environment:
      name: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0          # required to create & push tags

      - name: Compute tag (UTC timestamp)
        id: meta
        run: |
          TS="$(date -u +%Y%m%d%H%M%S)"           # e.g. 20251022T152312 -> 20251022152312
          TAG="v0.0.0-${TS}"
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"
          echo "Generated tag: ${TAG}"

      - name: Create and push tag
        env:
          TAG: ${{ steps.meta.outputs.tag }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "${TAG}" -m "Automated pre-release from ${GITHUB_REF_NAME} at $(date -u -Iseconds)"
          git push origin "${TAG}"

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          check-latest: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 0
